version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: aidolist_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: haianh2309
      POSTGRES_DB: aidolist_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
      build: ./backend
      container_name: aidolist_backend
      restart: always
      ports:
        - "5000:5000"
      depends_on:
        - db
        - ai_service
      environment:
        DATABASE_URL: postgres://postgres:haianh2309@db:5432/aidolist_db
        AI_SERVICE_URL: http://ai_service:8000
        INTERNAL_API_KEY: "secret_internal_key_123"
      extra_hosts:
        - "host.docker.internal:host-gateway"
      volumes:
        - ./backend:/app
        - /app/node_modules

  ai_service:
      build: ./ai_service
      container_name: aidolist_ai_service
      restart: always
      ports:
        - "8000:8000"
      environment:
        INTERNAL_API_KEY: "secret_internal_key_123"
      extra_hosts:
        - "host.docker.internal:host-gateway"

  frontend:
      build: ./frontend
      container_name: aidolist_frontend
      ports:
        - "3000:3000"
      volumes:
        - ./frontend:/app
        - /app/node_modules
      environment:
        - NEXT_PUBLIC_API_URL=http://localhost:5000/api
      depends_on:
        - backend
volumes:
  postgres_data: