version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: aidolist_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: haianh2309
      POSTGRES_DB: aidolist_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: aidolist_redis
    ports:
      - "6379:6379"

  ai_service:
    build: ./ai_service
    container_name: aidolist_ai
    ports:
      - "8000:8000"
    volumes:
      - ./ai_service/models:/app/models 
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  backend:
    build: ./backend
    container_name: aidolist_backend
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
      - ai_service
    environment:
      DATABASE_URL: postgres://postgres:haianh2309@db:5432/aidolist_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AI_SERVICE_URL: http://ai_service:8000
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
      build: ./frontend
      container_name: aidolist_frontend
      ports:
        - "3000:3000"
      volumes:
        - ./frontend:/app
        - /app/node_modules
      environment:
        - NEXT_PUBLIC_API_URL=http://localhost:5000
      depends_on:
        - backend
volumes:
  postgres_data: